version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8082
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/library_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
networks:
  springapimysql-net: