version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - libraryapp-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/library_db?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: syed
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysqldb


  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - libraryapp-net
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234_r
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
networks:
  libraryapp-net: